// app/frontend/src/App.vue
<template>
  <span v-show="!hashed">
    <h1 class="text-8xl font-averia mt-40 dark:text-white">lil' hash</h1>
    <p class="text-2xl font-averia dark:text-white">
      simple sharable url shortener
    </p>
    <input
      v-model.trim="inputUrl"
      class="shadow-inner rounded-md text-2xl p-4 m-4 w-1/2 text-center my-10"
      @keyup.enter="hash"
    />
    <button
      class="bg-white shadow px-8 py-4 text-2xl rounded-md transition duration-500"
      :class="{ 'bg-red-500': error }"
      @click="hash"
    >
      {{ error ? "try again" : "hash" }}
    </button>
  </span>
  <span v-show="hashed">
    <p class="truncate mx-96 text-4xl font-averia mt-40 dark:text-white">
      {{ inputUrl }}
    </p>
    <p class="text-2xl my-4 font-averia dark:text-white">
      has been shortened to
    </p>
    <p class="text-8xl font-averia dark:text-white">
      {{ hashedUrl }}
    </p>
    <p class="text-2xl my-8 font-averia dark:text-white">
      for the next 24 hours
    </p>
  </span>
</template>

<script>
import axios from "axios";
const HOURS = 24;
export default {
  data() {
    return {
      inputUrl: "",
      hashedUrl: "",
      error: false,
      server: import.meta.env.VITE_SERVER_URL || "http://localhost:8000",
    };
  },
  computed: {
    hashed() {
      return this.hashedUrl.length > 0;
    },
  },
  methods: {
    hash() {
      console.log("hashing...");
      // eslint-disable-next-line
      axios.post(`${this.server}/hash?url=${encodeURIComponent(this.inputUrl)}&hours=${HOURS}`)
        .then((response) => {
          console.log("hashed!");
          console.log();
          const protocol_index = this.server.indexOf("://");
          this.hashedUrl =
            this.server.slice(protocol_index + 3) + "/" + response.data.key;
          this.error = false;
        })
        .catch(() => {
          this.error = true;
        });
    },
  },
};
</script>

<style>
.font-averia {
  font-family: "Averia Serif";
}
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
html {
  @apply bg-yellow-300 dark:bg-gray-900;
}
</style>

// app/frontend/src/App.svelte
<script>
import axios from "axios";
const HOURS = 24;
const SERVER = "https://lilhash.com"
let inputUrl = ""
let hashedUrl = ""
let error = false
$: hashed = hashedUrl.length > 0;
const hash = () => {
  // eslint-disable-next-line
  axios.post(`${SERVER}/hash?url=${encodeURIComponent(inputUrl)}&hours=${HOURS}`)
    .then((response) => {
      const protocol_index = SERVER.indexOf("://");
      hashedUrl = SERVER.slice(protocol_index + 3) + "/" + response.data.key;
      error = false;
    })
    .catch(() => {
      error = true;
    });
}

</script>

{#if !hashed}
<h1 class="text-4xl md:text-6xl lg:text-8xl font-averia mt-40 dark:text-white">lil' hash</h1>
<p class="text-xl lg:text-2xl font-averia dark:text-white">
  simple sharable url shortener
</p>
<input
  bind:value={inputUrl}
  class="shadow-inner rounded-md text-md w-3/5 md:w-1/2 lg:text-2xl p-2 md:p-3 lg:p-4 m-4 lg:my-10 text-center"
  on:keyup={(e) => e.key==='Enter' && hash()}
/>
<button
  class="px-3 md:px-5 lg:px-8 py-2 md:py-3 lg:py-4 text-md lg:text-2xl rounded-md transition duration-500 bg-white shadow"
  class:bg-red-500={error}
  on:click={hash}
>
  { error ? "try again" : "hash" }
</button>
{:else}
<p class="text-md md:text-lg lg:text-2xl my-4 mt-40 font-averia dark:text-white">
  your link been shortened to
</p>
<p class="text-3xl md:text-5xl lg:text-6xl xl:text-7xl font-averia dark:text-white">
  { hashedUrl }
</p>
<p class="text-md md:text-lg lg:text-2xl m-4 md:m-5 lg:m-8 font-averia dark:text-white">
  for the next 24 hours
</p>
{/if}

<style>
.font-averia {
  font-family: "Averia Serif";
  font-weight: 300;
}
</style>
